version: "3"

services:
  web-app:
    build:
      context: ./web-app
      dockerfile: ./Dockerfile
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://user:password@db:5432/apteka
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: "apteka"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432